class TokenType:
    BEGIN = 'BEGIN'
    COMMA = 'COMMA'
    IDENTIFIER = 'IDENTIFIER'
    PERIOD = 'PERIOD'
    ASSIGN = 'ASSIGN'
    NUMBER = 'NUMBER'
    IF = 'IF'
    LESS_THAN = 'LESS_THAN'
    THEN = 'THEN'
    PRINT = 'PRINT'
    STRING = 'STRING'
    ELSE = 'ELSE'
    END = 'END'